# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [2]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

type(my_numpy_array)

numpy.ndarray

In [3]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([ [2, 5, 8],[7,3,6] ])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [4]:
mini_c1 = np.array([ [3,7,9,3],[4,3,2,2] ])
mini_c1

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [5]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.61474702, 0.58626571, 0.19016912, 0.3402125 , 0.46056136,
       0.92706915, 0.18173382, 0.78529403, 0.01787836, 0.93069053,
       0.52965069, 0.95244443, 0.16488869, 0.47833672, 0.39073381,
       0.02358619, 0.9697364 , 0.09622978, 0.60017791, 0.38990216])

In [6]:
# you can create a matrix of random number as well
x = np.random.rand(3,3)
x

array([[0.36319508, 0.78787535, 0.06469555],
       [0.77295565, 0.09998377, 0.63777028],
       [0.43487035, 0.91441734, 0.89218585]])

In [7]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,50)
x

4

In [8]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,100,15)
x

array([82, 80, 79,  8, 15, 95, 48, 73,  7, 13, 43,  8, 27, 10, 57])

In [9]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [46]:
# create a diagonal of ones and zeros everywhere else
y = np.eye(7)
y

#The periods following each entry here is because they're floating point values.
#Convert to ints to get rid of the period.

y = y.astype(int)
y

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [11]:
# Matrix of ones
x = np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# Array of zeros
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [41]:
#This is how I did it
val = input("Please enter a positive integer")
x = np.random.randint(1,val,10)
#This step is superfluous because the randint function outputs as an array
#my_numpy_array = np.array(x)
x

#Apparently randint is with replacement.

#This is how he did it. More compact.
#x = int(input('Please enter a positive integer value'))
#x = np.random.randint(1,x,10)
#x

Please enter a positive integer10


array([3, 3, 6, 2, 6, 4, 4, 2, 4, 1])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [14]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [18]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [20]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])
#I didn't spend very long looking up the correct distance formula.
#There were lots of options so instead I just got the abs of the diff. Same idea.
diff = np.abs(x - y)
diff

#He did:
z = np.sqrt(x**2 + y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [21]:
my_numpy_array = np.array([3,5,6,2,8,10,20,50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [22]:
# Access specific index from the numpy array
#Get first element
my_numpy_array[0]

#Get last element
my_numpy_array[-1]
#Get 2nd to last element
my_numpy_array[-2]


20

In [23]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[0:3]

array([3, 5, 6])

In [24]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array
#array([ 7,  7,  7,  7,  8, 10, 20, 50])

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [25]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10,(4,4))
matrix

array([[1, 9, 1, 1],
       [3, 7, 8, 3],
       [7, 5, 8, 2],
       [8, 8, 5, 9]])

In [26]:
# Get a row from a matrix
matrix[0]
matrix[1]
matrix[-1]

array([8, 8, 5, 9])

In [27]:
# Get one element
#matrix[row][column]
matrix[3][2]


5

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [28]:
#I did it exactly the same as the instructor
x = np.array([
    [2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37] 
])
#Now use broadcasting
x[4] = 0
x

#You could also have done x[-1] = 0 for the same effect

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [29]:
matrix = np.random.randint(1,10,(5,5))
matrix

array([[5, 4, 3, 9, 3],
       [7, 3, 2, 6, 6],
       [7, 1, 9, 6, 4],
       [2, 3, 2, 8, 3],
       [6, 9, 1, 9, 4]])

In [30]:
new_matrix = matrix[matrix > 7]
new_matrix

array([9, 9, 8, 9, 9])

In [31]:
# Obtain odd elements only
matrix_odd = matrix[matrix % 2 > 0]
matrix_odd

matrix_even = matrix[matrix % 2 == 0]
matrix_even

array([4, 2, 6, 6, 6, 4, 2, 2, 8, 6, 4])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [32]:
x = np.array([
    [2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]
])
x[x < 0] = 0
x[x % 2 == 1] = -2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [33]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [34]:
import pandas as pd

In [35]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                              'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                              'Net Worth':[7500, 29000,10000,2000],
                              'Years with Bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth  Years with Bank
0             111           Chanel       7500                3
1             222            Steve      29000                4
2             333            Mitch      10000                9
3             444             Ryan       2000                5

In [36]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [37]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth  Years with Bank
0             111           Chanel       7500                3
1             222            Steve      29000                4

In [38]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth  Years with Bank
2             333            Mitch      10000                9
3             444             Ryan       2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [39]:
portfolio_df = pd.DataFrame({'Ticker':['APPLE', 'AMZN', 'GOOGL'],
                              'SharesCount':[10,5,20],
                              'PricePerShare':[2,5,3]})
portfolio_df
#This is how I did it
#x = sum(portfolio_df['SharesCount'] * portfolio_df['PricePerShare'])
#x
sum(portfolio_df['SharesCount'] * portfolio_df['PricePerShare'])

#He did:
#stocks_dollar_value = portfolio_df['PricePerShare'] * portfolio_df['SharesCount']
#stocks_dollar_value.sum()

TypeError: 'numpy.ndarray' object is not callable

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [ ]:
# Pandas is used to read a csv file and store data in a DataFrame
#He didn't do this but I'm going to try it now
#There were some encoding issues that crossed over copying one of the Canada Homes tables
#into LibreOffice. The encoding bit fixed it. You might not need that normally.
csv_test = pd.read_csv(r'C:\Users\Administrator\Desktop\CanadaHomes.csv', encoding='cp1252')
csv_test

In [ ]:
!pip3 install lxml
!python -m pip install --upgrade pip
#You need to restart the Kernel after you run this

In [ ]:
# Read tabular data using read_html
#import pandas as pd
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]
#The [0] finds the first table in the html. Cool!

In [ ]:
house_price_df[1]

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
nra = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
nra[0]

# TASK #8: PANDAS OPERATIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                              'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                              'Net Worth':[7500, 29000,10000,2000],
                              'Years with Bank':[3,4,9,5]})
bank_client_df

In [ ]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[bank_client_df['Years with Bank']>=5]
df_loyal

In [ ]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                              'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                              'Net Worth':[7500, 29000,10000,2000],
                              'Years with Bank':[3,4,9,5]})
#bank_client_df

high_rollers = bank_client_df[bank_client_df['Net Worth']>=5000]
sum(high_rollers['Net Worth'])
#He did
#high_rollers['Net Worth'].sum()

# TASK #9: PANDAS WITH FUNCTIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                              'Bank Client Name':['Chanel','Steve','Mitch','Ryan'],
                              'Net Worth':[7500, 29000,10000,2000],
                              'Years with Bank':[3,4,9,5]})
bank_client_df


In [ ]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2

In [ ]:
# You can apply a function to the DataFrame 
bank_client_df['Net Worth'].apply(networth_update)

In [ ]:
bank_client_df['Bank Client Name'].apply(len)

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
portfolio_df = pd.DataFrame({'Ticker':['APPLE', 'AMZN', 'GOOGL'],
                              'SharesCount':[10,5,20],
                              'PricePerShare':[2,5,3]})

def f_mc9_update(new_stock_price):
    return (new_stock_price*3)+200
#I did it this way
sum(portfolio_df['PricePerShare'].apply(f_mc9_update))

#I bet he does it this way.
#portfolio_df['PricePerShare'].apply(f_mc9_update).sum()

#He only sort of did!
#results = portfolio_df['PricePerShare'].apply(f_mc9_update)
#results.sum()

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

In [ ]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

In [ ]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df.sort_values(by = 'Years with bank', inplace = True)
bank_client_df

In [ ]:
# Set inplace = True to ensure that change has taken place in memory 


In [ ]:
# Note that now the change (ordering) took place 


# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [ ]:
df1 = pd.DataFrame({'A': ['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C': ['C0','C1','C2','C3'],
                    'D': ['D0','D1','D2','D3']
                   },index = [0,1,2,3])

df2 = pd.DataFrame({'A': ['A4','A5','A6','A7'],
                    'B':['B4','B5','B6','B7'],
                    'C': ['C4','C5','C6','C7'],
                    'D': ['D4','D5','D6','D7']
                   },index = [4,5,6,7])

df3 = pd.DataFrame({'A': ['A8','A9','A10','A11'],
                    'B':['B8','B9','B10','B11'],
                    'C': ['C8','C9','C10','C11'],
                    'D': ['D8','D9','D10','D11']
                   },index = [8,9,10,11])

df3

In [ ]:
pd.concat([df1,df2,df3])

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'client_id':[1,2,3,4,5],
                  'client_fname':['Taryn', 'Hugh', 'Laurel','Rachel','Donovan'],
                  'client_lname': ['Popplewell', 'Noble', 'Popplewell','Dana','Unknown']}
                   #,index = [0,1,2,3,4]
                  )

df2 = pd.DataFrame({'client_id':[6,7,8,9,10],
                  'client_fname':['Jenny', 'Josh', 'Liz','Nick','James'],
                  'client_lname': ['Murphy', 'Ready', 'Malloy','McCann','McCann']}
                   #, index = [5,6,7,8,9]
                  )

df3 = pd.DataFrame({'client_id': [1,2,3,4,5,6,7,8,9,10],
                   'annual_salary':[135000,93000,160000,50000,50000,160000,75000,100000,45000,0]})

df4 = pd.concat([df1,df2])
type(df4)

all_bank_clients = df4.merge(df3, on='client_id', how='inner')

df5 = pd.DataFrame({'client_id':[11],
                  'client_fname':['Alan'],
                  'client_lname': ['Rickman'],
                   'annual_salary': [16000000]})

pd.concat([all_bank_clients,df5])
all_bank_clients.tail()

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200 

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df